name: Build Tweak
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install base packages
        run: sudo apt update && sudo apt install -y git curl build-essential libtinfo6 rsync perl fakeroot

      - name: Install Theos official script
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          # 新增：自动下载最新iOS SDK
          $HOME/theos/bin/install-sdk latest

      - name: Build package (rootless for Dopamine)
        run: make package FINALPACKAGE=1
      
      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          name: tweak-deb
          path: packages/*.deb